"""Add Digital Twin models

Revision ID: 51988d01057c
Revises: 
Create Date: 2025-11-29 13:15:42.933135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51988d01057c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_script', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_persona', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quiz_data', sa.JSON(), nullable=True))
        batch_op.alter_column('risk_score',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('primary_script')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('tags')
        batch_op.drop_column('risk_level')

    with op.batch_alter_table('money_script', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_script', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('risk_score',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('quiz_data')
        batch_op.drop_column('primary_persona')

    # ### end Alembic commands ###
