"""Add RecurringBill model

Revision ID: 9b43fa77719c
Revises: 51988d01057c
Create Date: 2025-11-30 11:42:57.557847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b43fa77719c'
down_revision = '51988d01057c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('average_amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('last_paid_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_bill')
    # ### end Alembic commands ###
